version: '3.8'

services:
  takatalk-db:
    image: mariadb:${MARIADB_VERSION}
    container_name: takatalk-mariadb
    restart: always
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}  #여기서 설정한값들이 실제 DB의 접속정보가 됩니다.
      MARIADB_DATABASE: ${MARIADB_NAME}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql # 내컴퓨터 폴더 : 컨테이너 내부 폴더 연결. DB를 지워도 데이터 남음(내컴퓨터에 남게된다는 뜻인듯)
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s # 10초마다 체크
      timeout: 5s # 응답이 5초가 넘으면 실패로 간주
      retries: 5 # 5번 연속 실패하면 'unhealthy' 상태로 표시
      start_period: 30s # 초기부팅시 30초 동안은 실패해도 봐줌. (초기화 시간 배려)
      # mariadb-admin 명령어로 접속이 가능한지 10초마다 확인한다.
  controller:
    image: ngrinder/controller:latest
    container_name: ngrinder-controller
    restart: always
    mem_limit: 1g     # 메모리 제한 추가
    ports:
      - "${NGRINDER_PORT}:80"     # 웹 UI 접속포트
      - "${NGRINDER_AGENT_PORT}:16001" # Agent 연결 포트
      - "${NGRINDER_AGENT_TRANS_PORT}:12000-12010" # 테스트 실행시 컨트롤러-에이전트 통신 포트
    volumes:
      - ${NGRINDER_DATA_PATH}:/opt/ngrinder-controller
  agent:  # 실제로 부하를 발생시키는 담당
    image: ngrinder/agent:latest
    container_name: ngrinder-agent
    restart: always
    mem_limit: 512m     # 메모리 제한 추가
    environment:
      - GRINDER_CONTROLLER_IP=ngrinder-controller
      - GRINDER_CONTROLLER_PORT=${NGRINDER_AGENT_PORT}
    links:
      - controller



