version: '3.8'

services:
  takatalk-db:
    image: mariadb:${MARIADB_VERSION}
    container_name: takatalk-mariadb
    restart: always
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}  #여기서 설정한값들이 실제 DB의 접속정보가 됩니다.
      MARIADB_DATABASE: ${MARIADB_NAME}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql # 내컴퓨터 폴더 : 컨테이너 내부 폴더 연결. DB를 지워도 데이터 남음(내컴퓨터에 남게된다는 뜻인듯)
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"


