server:
  port: 9000

spring:
  config:
    import: optional:env-dev.yml

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/takatalk # 도커설정 포트, DB이름 확인하기
    username: ${MARIADB_USER} # 도커에 설정한 username, password
    password: ${MARIADB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 처음엔 update
    properties:
      hibernate:
        #show_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오는 id를 식별자로 사용함.

custom:
  site:
    front-url: http://localhost:5173


logging:
  level:
    com.example.chat: info
    #org.hibernate.SQL: debug

