# 공통설정
#env.yml
spring:
  config:
    import: optional:env.yml

  application:
    name: chat

  jpa:
    properties:
      hibernate:
        format_sql: true  # 가독성좋게 포맷팅
        jdbc:
          batch_size: 50  # 한번에 전송할수있는 SQL문의 개수 (일괄처리)
        order_inserts: true


  #에러처리
  messages:
    encoding: UTF-8
    basename: errors, messages

  #smtp
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  #SECURITY
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

#BASE_URL
app:
  base-url: ${BASE_URL}

# FILE UPLOAD PATH
file:
  upload:
    upload-path: ${UPLOAD_DIR}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24시간 (ms)